### ISSUE TITLE
Doesn't find PyCharm Professional projects

### ISSUE THREAD

**Issue by lephuongbg** [alex1701c/JetBrainsRunner#1]
First let me thank you for this lovely runner. I had just the idea to write one and already found this on KDE Store.

My issue is that I have PyCharm and PhpStorm on my machine. This runner only finds PhpStorm projects, but not PyCharm ones. I'm more than happy to send any log needed.

**Comment by alex1701c** [comment]
Thank you for your feedback !

I have just made a few additions to the code which should make finding the problem easier.   
Please download the new changes and go to the CMakeLists.txt of the project root and uncomment the line "add_compile_definitions(LOG_INSTALLED)" , recompile your project and restart your runner with `kquitapp5 krunner;kstart5 krunner `.

These messages will be very helpful 😃
Additionally the .desktop file of PyCharm is needed and it would be useful to know how you have the apps installed (Jetbrains Toolbox/Snap/Website).

Edit: It would also be useful to know if you have/had installed other PyCharm apps, like the community or educational version.

**Comment by lephuongbg** [comment]
Noop question but how do I get the debug output of the plugin? I have already recompiled per your instruction.

**Comment by lephuongbg** [comment]
And also my PyCharm installation is from Toolbox.

**Comment by alex1701c** [comment]
First of all do you have the latest version of this plugin installed ?
And I forgot to mention that you have to load the runner by executing:
`kquitapp5 krunner;kstart5 krunner;qdbus org.kde.krunner /App org.kde.krunner.App.query "test"`

This restarts the runner and launches it with "test" as query, only if it gets launched with a query the plugins get initialized.

And it would be useful to get the PyChram .dektop file located at `~/.local/share/applications/jetbrains-pycharm.desktop` 

Thank You !

PS: I unfortunately haven't been able to reproduce your issue on a VM.

**Comment by lephuongbg** [comment]
Actually my PyCharm desktop file is at ~/.local/share/applications/jetbrains-pycharm-1.desktop.

**Comment by lephuongbg** [comment]
That could be due to I installed EAP/RC version and then delete the main version.

**Comment by alex1701c** [comment]
Edit: I think I have found this problem, I was not aware of the EAP/RC versions, if I have further questions/the solution I will comment it 😃

**Comment by alex1701c** [comment]
I have just committed some changes:
The EAP/RC versions now find the config files and I had to rewrite the logic of the XML reader because the structure is sometimes different.

Please let me know if this fixes the issue 😀

**Comment by lephuongbg** [comment]
Hi, I've already pulled the latest code and recompiled. It seems you have found a different bug. Because my PyCharm has already been upgraded to final (non-RC) version.

Here is my desktop file content

```
[Desktop Entry]
Categories=Development;IDE;
Comment=Python IDE for professional developers
Exec="/home/lephuong/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-1/192.6603.34/bin/pycharm.sh" %f
Icon=/home/lephuong/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-1/.icon.svg
Name=PyCharm Professional Release
StartupWMClass=jetbrains-pycharm
Terminal=false
Type=Application
Version=1.0
```

**Comment by lephuongbg** [comment]
By the way, I still don't see any output from the terminal. If I run PhpStorm using the runner, I do see PhpStorm's logging output though. Do I need to set some environment variable so `qInfo()` will show up?

**Comment by alex1701c** [comment]
> Hi, I've already pulled the latest code and recompiled. It seems you have found a different bug. Because my PyCharm has already been upgraded to final (non-RC) version.
> 
> Here is my desktop file content
> 
> ```
> [Desktop Entry]
> Categories=Development;IDE;
> Comment=Python IDE for professional developers
> Exec="/home/lephuong/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-1/192.6603.34/bin/pycharm.sh" %f
> Icon=/home/lephuong/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-1/.icon.svg
> Name=PyCharm Professional Release
> StartupWMClass=jetbrains-pycharm
> Terminal=false
> Type=Application
> Version=1.0
> ```

Ok this is now another minor issue than I initially thought.
Please check if the latest commit fixes the issue.

**Comment by alex1701c** [comment]
It is weird that you get no debug output. If you have the definition uncommented and the project recompiled you should see something like this (except you should have less applications😉):

![debug_output_demonstration](https://user-images.githubusercontent.com/38406607/65015457-eb84ae00-d921-11e9-8623-fc9804e54a16.gif)

**Comment by lephuongbg** [comment]
That's strange. I did exactly the same and there was no output at all.
Already tried your latest commit and no luck yet.

Following are my options directory:

```
/home/lephuong/.PhpStorm2018.2/config/options/recentProjectDirectories.xml
/home/lephuong/.PhpStorm2019.1/config/options/recentProjectDirectories.xml
/home/lephuong/.PhpStorm2019.2/config/options/recentProjectDirectories.xml
/home/lephuong/.PyCharm2019.1/config/options/recentProjectDirectories.xml
/home/lephuong/.PyCharm2019.2/config/options/recentProjectDirectories.xml
```

**Comment by alex1701c** [comment]
That is really strange and I have currently no idea why it does not work 🤔

Are you sure that you have pulled the latest changes and recompiled your project and restarted the runner ?(Sorry for asking)
You can try to reinstall the project from the ground up:
` curl https://raw.githubusercontent.com/alex1701c/JetBrainsRunner/master/install.sh | bash`

And look if this has some effects.
If not there can only be an issue with reading the `/home/lephuong/.PyCharm2019.2/config/options/recentProjectDirectories.xml` file. 
Because I have copied your .desktop file on my setup and removed all my jetbrains-pycharm* files and he finds the ` ~/.PyCharm2019.2/config/options/recentProjectDirectories.xml` file and reads the entries correctly. 

Could you please upload this file? 🙃

**Comment by lephuongbg** [comment]
Wow. It's working now. I've removed the old src and run your script again and now all projects are showing. Thanks very much for your patience and this lovely runner.
