### ISSUE TITLE
Rider 2020.1 no projects found

### ISSUE THREAD

**Issue by ghost** [alex1701c/JetBrainsRunner#14]
I am using JetBrainsRunner 1.5.0 
IntelliJ 2019.3 works great out of the box, but for some reason Rider doesn't find any recent projects, even after configuring manually. 

Here is the log and my config. The paths are 100% correct. It is correct that there are no current Android Studio projects, I don't have any right now.
![image](https://user-images.githubusercontent.com/10449980/91170610-6d0bc100-e6d9-11ea-96f6-2ad226b2a613.png)

recentSolutions.xml

```xml

<application>
  <component name="RiderRecentProjectsManager">
    <option name="additionalInfo">
      <map>
        <entry key="$USER_HOME$/UnityProjects/tower-defense/tower-defense.sln">
          <value>
            <RecentProjectMetaInfo projectWorkspaceId="1Xp54tfcoj209watEav62AEtouT">
              <option name="binFolder" value="$APPLICATION_HOME_DIR$/bin" />
              <option name="build" value="RD-201.7846.1" />
              <option name="buildTimestamp" value="1589564119082" />
              <frame x="-1" y="-1" width="1922" height="1052" extendedState="6" />
              <option name="productionCode" value="RD" />
              <option name="projectOpenTimestamp" value="1591299440116" />
            </RecentProjectMetaInfo>
          </value>
        </entry>
        <entry key="$USER_HOME$/UnityProjects/Pentecost/Pentecost.sln">
          <value>
            <RecentProjectMetaInfo projectWorkspaceId="1croOZAyyvczxsZ4V2cQJTlXD2X">
              <option name="binFolder" value="$APPLICATION_HOME_DIR$/bin" />
              <option name="build" value="RD-201.7846.1" />
              <option name="buildTimestamp" value="1589564115550" />
              <option name="productionCode" value="RD" />
              <option name="projectOpenTimestamp" value="1591643202778" />
            </RecentProjectMetaInfo>
          </value>
        </entry>
        <entry key="$USER_HOME$/Projects/Blazor/ComponentLibrary/ComponentLibrary.sln">
          <value>
            <RecentProjectMetaInfo opened="true" projectWorkspaceId="1cEPcSigXVSIwQ5f6RWQafItRpz">
              <option name="binFolder" value="$APPLICATION_HOME_DIR$/bin" />
              <option name="build" value="RD-201.7846.1" />
              <option name="buildTimestamp" value="1589564150214" />
              <frame x="-4" y="-1" width="1928" height="1055" extendedState="6" />
              <option name="productionCode" value="RD" />
              <option name="projectOpenTimestamp" value="1597069979098" />
            </RecentProjectMetaInfo>
          </value>
        </entry>
      </map>
    </option>
    <option name="lastProjectLocation" value="$USER_HOME$/Projects" />
    <option name="recentPaths">
      <list>
        <option value="$USER_HOME$/Projects/Blazor/ComponentLibrary/ComponentLibrary.sln" />
        <option value="$USER_HOME$/UnityProjects/Pentecost/Pentecost.sln" />
        <option value="$USER_HOME$/UnityProjects/tower-defense/tower-defense.sln" />
      </list>
    </option>
  </component>
</application>

```

**Comment by alex1701c** [comment]
Thanks for the report! I will look into it tomorrow :)

**Comment by alex1701c** [comment]
It seems like the structure of the XML file is different. That is why the projects can not be read. Also the file is called recentSolutions.xml and not recentProjects.xml or recentProjectDirectories.xml.

**Comment by ghost** [comment]
Isn't the xml structure the same as in https://github.com/alex1701c/JetBrainsRunner/issues/10 ?


The file name is only an issue for automatic detection, not for the manual one right?

**Comment by alex1701c** [comment]
>The file name is only an issue for automatic detection, not for the manual one right?

Exactly!

>Isn't the xml structure the same as in #10 ?

It is a bit different:
```xml
<option name="lastProjectLocation" value="$USER_HOME$/Projects" />
```

In the mentioned issue this information is saved differently and not in an extra option:
```xml
<RecentProjectMetaInfo opened="true" projectWorkspaceId="1OSe59a47F5s7Ju2yf95mDpCg66">
```

**Comment by alex1701c** [comment]
Heyho,

I have merged the work branch of this plugin and added the `rewrite_xml_parsing` branch to the submodule. Please update the plugin and the src/jetbrains-api submodule.

I have tried it out and it works for me out of the box, so please try to remove the manual mapping entry. But it is still WIP.

Thank you :-)

**Comment by ghost** [comment]
Still no luck. 
I uninstalled the previous version, pulled the repo, updated submodules, followed the install instructions. Did a complete system restart just in case.
The log file changed, which I take as a success in updating the JetbrainsRunner.

When I don't have a manual config the logfile outputs:

```
========== Locally Installed Jetbrains Applications ==========
/home/deckweiss/.local/share/applications/jetbrains-idea.desktop
/home/deckweiss/.local/share/applications/jetbrains-rider.desktop
========== Globally Installed Jetbrains Applications ==========
========== AUR/Snap/Other Installed Jetbrains Applications ==========
========== Manually Configured Jetbrains Applications ==========
Application path map: 
IntelliJ IDEA Ultimate ==> /home/deckweiss/.local/share/applications/jetbrains-idea.desktop
JetBrains Rider ==> /home/deckweiss/.local/share/applications/jetbrains-rider.desktop
========== Find Available Config Folders ==========
Rider /home/deckweiss/.config/JetBrains/Rider2020.1
IntelliJIdea /home/deckweiss/.IntelliJIdea2019.3
AndroidStudio /home/deckweiss/.AndroidStudio3.5
IntelliJ IDEA Ultimate /home/deckweiss/.IntelliJIdea2019.3/config/options/  from alias
JetBrains Rider is not contained in alias
Config file found for IntelliJ IDEA Ultimate /home/deckweiss/.IntelliJIdea2019.3/config/options/recentProjects.xml
===== Recently used project folder for IntelliJ IDEA Ultimate=====
    /home/deckweiss/Work/eloonline/ecm-solution-boot/frontend
    /home/deckweiss/Work/eloonline
    /home/deckweiss/Work/document-extraction-api
    /home/deckweiss/Work/spiketime-accountant
    /home/deckweiss/Uni/Aktuell/MCIM/Aufgaben/Lösungen/Klausurvorbereitung
    /home/deckweiss/Uni/Aktuell/MCIM/Aufgaben/Lösungen/SetupExample
    /home/deckweiss/Work/datevwebapp

========== Filter Jetbrains Apps ==========
Found not projects for: JetBrains Rider

```

What is more interesting is the log when I add the manual entry:

```
========== Locally Installed Jetbrains Applications ==========
/home/deckweiss/.local/share/applications/jetbrains-idea.desktop
/home/deckweiss/.local/share/applications/jetbrains-rider.desktop
========== Globally Installed Jetbrains Applications ==========
========== AUR/Snap/Other Installed Jetbrains Applications ==========
========== Manually Configured Jetbrains Applications ==========
/home/deckweiss/.local/share/applications/jetbrains-rider.desktop
/home/deckweiss/.config/JetBrains/Rider2020.1/options/recentSolutions.xml
Application path map: 
IntelliJ IDEA Ultimate ==> /home/deckweiss/.local/share/applications/jetbrains-idea.desktop
JetBrains Rider ==> /home/deckweiss/.local/share/applications/jetbrains-rider.desktop
========== Custom Configured Applications ==========
JetBrains Rider the project path does not exist /home/deckweiss/Projects/Blazor/ComponentLibrary/ComponentLibrary.sln
JetBrains Rider the project path does not exist /home/deckweiss/UnityProjects/Pentecost/Pentecost.sln
JetBrains Rider the project path does not exist /home/deckweiss/UnityProjects/tower-defense/tower-defense.sln
===== Recently used project folder for JetBrains Rider=====
    NO PROJECTS

========== Find Available Config Folders ==========
Rider /home/deckweiss/.config/JetBrains/Rider2020.1
IntelliJIdea /home/deckweiss/.IntelliJIdea2019.3
AndroidStudio /home/deckweiss/.AndroidStudio3.5
IntelliJ IDEA Ultimate /home/deckweiss/.IntelliJIdea2019.3/config/options/  from alias
Config file found for IntelliJ IDEA Ultimate /home/deckweiss/.IntelliJIdea2019.3/config/options/recentProjects.xml
===== Recently used project folder for IntelliJ IDEA Ultimate=====
    /home/deckweiss/Work/eloonline/ecm-solution-boot/frontend
    /home/deckweiss/Work/eloonline
    /home/deckweiss/Work/document-extraction-api
    /home/deckweiss/Work/spiketime-accountant
    /home/deckweiss/Uni/Aktuell/MCIM/Aufgaben/Lösungen/Klausurvorbereitung
    /home/deckweiss/Uni/Aktuell/MCIM/Aufgaben/Lösungen/SetupExample
    /home/deckweiss/Work/datevwebapp

========== Filter Jetbrains Apps ==========

```


It seems to find the projects, but claims that the path doesnt exist, even though it clearly does. 
My wild guess: Is that maybe a permissions or drive(nvme ssd) issue?

**Comment by alex1701c** [comment]
Could you please provide the content of `~/.local/share/applications/jetbrains-rider.desktop`? That might give a hint on why the autodetection does not work.

Also I have added debug information for the file, so we can see if it exists/is readable etc. So please update the src/jetbrains-api  rewrite_xml_parsing branch and reinstall the project and provide the log output. Thanks :)

**Comment by ghost** [comment]
This is the content of ~/.local/share/applications/jetbrains-rider.desktop

```
[Desktop Entry]
Categories=Development;IDE;
Comment=A cross-platform IDE for .NET
Exec="/home/deckweiss/.JetBrains Rider-2020.1.3/bin/rider.sh" %f
Icon=/home/deckweiss/.JetBrains Rider-2020.1.3/bin/rider.png
Name=JetBrains Rider
NoDisplay=false
Path[$e]=
StartupNotify=true
StartupWMClass=jetbrains-rider
Terminal=0
TerminalOptions=
Type=Application
Version=1.0
X-KDE-SubstituteUID=false
X-KDE-Username=
```

I've switched the jetbrains-api submodule to the rewrite_xml_parsing branch and did a complete reinstall. This is the output without a manual entry:

```
========== Locally Installed Jetbrains Applications ==========
/home/deckweiss/.local/share/applications/jetbrains-idea.desktop
/home/deckweiss/.local/share/applications/jetbrains-rider.desktop
========== Globally Installed Jetbrains Applications ==========
========== AUR/Snap/Other Installed Jetbrains Applications ==========
========== Manually Configured Jetbrains Applications ==========
Application path map: 
IntelliJ IDEA Ultimate ==> /home/deckweiss/.local/share/applications/jetbrains-idea.desktop
JetBrains Rider ==> /home/deckweiss/.local/share/applications/jetbrains-rider.desktop
========== Find Available Config Folders ==========
Rider /home/deckweiss/.config/JetBrains/Rider2020.1
IntelliJIdea /home/deckweiss/.IntelliJIdea2019.3
AndroidStudio /home/deckweiss/.AndroidStudio3.5
IntelliJ IDEA Ultimate /home/deckweiss/.IntelliJIdea2019.3/config/options/  from alias
JetBrains Rider is not contained in alias
Config file found for IntelliJ IDEA Ultimate /home/deckweiss/.IntelliJIdea2019.3/config/options/recentProjects.xml
Config file found for IntelliJ IDEA Ultimate /home/deckweiss/.IntelliJIdea2019.3/config/options/recentProjects.xml
<<<<<<<<<<<<<<<</home/deckweiss/Work/eloonline/ecm-solution-boot/frontend Exists:true IsFile: false IsDir:true IsReadbale: true<<<<<<<<<<<<<<<</home/deckweiss/Work/eloonline Exists:true IsFile: false IsDir:true IsReadbale: true<<<<<<<<<<<<<<<</home/deckweiss/Work/document-extraction-api Exists:true IsFile: false IsDir:true IsReadbale: true<<<<<<<<<<<<<<<</home/deckweiss/Work/spiketime-accountant Exists:true IsFile: false IsDir:true IsReadbale: true<<<<<<<<<<<<<<<</home/deckweiss/Uni/Aktuell/MCIM/Aufgaben/Lösungen/Klausurvorbereitung Exists:true IsFile: false IsDir:true IsReadbale: true<<<<<<<<<<<<<<<</home/deckweiss/Uni/Aktuell/MCIM/Aufgaben/Lösungen/SetupExample Exists:true IsFile: false IsDir:true IsReadbale: true<<<<<<<<<<<<<<<</home/deckweiss/Work/datevwebapp Exists:true IsFile: false IsDir:true IsReadbale: true===== Recently used project folder for IntelliJ IDEA Ultimate=====
    /home/deckweiss/Work/eloonline/ecm-solution-boot/frontend
    /home/deckweiss/Work/eloonline
    /home/deckweiss/Work/document-extraction-api
    /home/deckweiss/Work/spiketime-accountant
    /home/deckweiss/Uni/Aktuell/MCIM/Aufgaben/Lösungen/Klausurvorbereitung
    /home/deckweiss/Uni/Aktuell/MCIM/Aufgaben/Lösungen/SetupExample
    /home/deckweiss/Work/datevwebapp

========== Filter Jetbrains Apps ==========
Found not projects for: JetBrains Rider
```


When I add the manual entiy **it now works**!

This is the output

```
========== Locally Installed Jetbrains Applications ==========
/home/deckweiss/.local/share/applications/jetbrains-idea.desktop
/home/deckweiss/.local/share/applications/jetbrains-rider.desktop
========== Globally Installed Jetbrains Applications ==========
========== AUR/Snap/Other Installed Jetbrains Applications ==========
========== Manually Configured Jetbrains Applications ==========
/home/deckweiss/.local/share/applications/jetbrains-rider.desktop
/home/deckweiss/.config/JetBrains/Rider2020.1/options/recentSolutions.xml
Application path map: 
IntelliJ IDEA Ultimate ==> /home/deckweiss/.local/share/applications/jetbrains-idea.desktop
JetBrains Rider ==> /home/deckweiss/.local/share/applications/jetbrains-rider.desktop
========== Custom Configured Applications ==========
Config file found for JetBrains Rider <application>
  <component name="RiderRecentProjectsManager">
    <option name="additionalInfo">
      <map>
        <entry key="$USER_HOME$/UnityProjects/tower-defense/tower-defense.sln">
          <value>
            <RecentProjectMetaInfo projectWorkspaceId="1Xp54tfcoj209watEav62AEtouT">
              <option name="binFolder" value="$APPLICATION_HOME_DIR$/bin" />
              <option name="build" value="RD-201.7846.1" />
              <option name="buildTimestamp" value="1589564119082" />
              <frame x="-1" y="-1" width="1922" height="1052" extendedState="6" />
              <option name="productionCode" value="RD" />
              <option name="projectOpenTimestamp" value="1591299440116" />
            </RecentProjectMetaInfo>
          </value>
        </entry>
        <entry key="$USER_HOME$/UnityProjects/Pentecost/Pentecost.sln">
          <value>
            <RecentProjectMetaInfo projectWorkspaceId="1croOZAyyvczxsZ4V2cQJTlXD2X">
              <option name="binFolder" value="$APPLICATION_HOME_DIR$/bin" />
              <option name="build" value="RD-201.7846.1" />
              <option name="buildTimestamp" value="1589564115550" />
              <option name="productionCode" value="RD" />
              <option name="projectOpenTimestamp" value="1591643202778" />
            </RecentProjectMetaInfo>
          </value>
        </entry>
        <entry key="$USER_HOME$/Projects/Blazor/ComponentLibrary/ComponentLibrary.sln">
          <value>
            <RecentProjectMetaInfo opened="true" projectWorkspaceId="1cEPcSigXVSIwQ5f6RWQafItRpz">
              <option name="binFolder" value="$APPLICATION_HOME_DIR$/bin" />
              <option name="build" value="RD-201.7846.1" />
              <option name="buildTimestamp" value="1589564118620" />
              <frame x="-4" y="-1" width="1928" height="1055" extendedState="6" />
              <option name="productionCode" value="RD" />
              <option name="projectOpenTimestamp" value="1599432819235" />
            </RecentProjectMetaInfo>
          </value>
        </entry>
      </map>
    </option>
    <option name="lastProjectLocation" value="$USER_HOME$/Projects" />
    <option name="recentPaths">
      <list>
        <option value="$USER_HOME$/Projects/Blazor/ComponentLibrary/ComponentLibrary.sln" />
        <option value="$USER_HOME$/UnityProjects/Pentecost/Pentecost.sln" />
        <option value="$USER_HOME$/UnityProjects/tower-defense/tower-defense.sln" />
      </list>
    </option>
  </component>
</application>
JetBrains Rider file content is empty 
========== Find Available Config Folders ==========
Rider /home/deckweiss/.config/JetBrains/Rider2020.1
IntelliJIdea /home/deckweiss/.IntelliJIdea2019.3
AndroidStudio /home/deckweiss/.AndroidStudio3.5
IntelliJ IDEA Ultimate /home/deckweiss/.IntelliJIdea2019.3/config/options/  from alias
Config file found for IntelliJ IDEA Ultimate /home/deckweiss/.IntelliJIdea2019.3/config/options/recentProjects.xml
Config file found for IntelliJ IDEA Ultimate /home/deckweiss/.IntelliJIdea2019.3/config/options/recentProjects.xml
<<<<<<<<<<<<<<<</home/deckweiss/Work/eloonline/ecm-solution-boot/frontend Exists:true IsFile: false IsDir:true IsReadbale: true<<<<<<<<<<<<<<<</home/deckweiss/Work/eloonline Exists:true IsFile: false IsDir:true IsReadbale: true<<<<<<<<<<<<<<<</home/deckweiss/Work/document-extraction-api Exists:true IsFile: false IsDir:true IsReadbale: true<<<<<<<<<<<<<<<</home/deckweiss/Work/spiketime-accountant Exists:true IsFile: false IsDir:true IsReadbale: true<<<<<<<<<<<<<<<</home/deckweiss/Uni/Aktuell/MCIM/Aufgaben/Lösungen/Klausurvorbereitung Exists:true IsFile: false IsDir:true IsReadbale: true<<<<<<<<<<<<<<<</home/deckweiss/Uni/Aktuell/MCIM/Aufgaben/Lösungen/SetupExample Exists:true IsFile: false IsDir:true IsReadbale: true<<<<<<<<<<<<<<<</home/deckweiss/Work/datevwebapp Exists:true IsFile: false IsDir:true IsReadbale: true===== Recently used project folder for IntelliJ IDEA Ultimate=====
    /home/deckweiss/Work/eloonline/ecm-solution-boot/frontend
    /home/deckweiss/Work/eloonline
    /home/deckweiss/Work/document-extraction-api
    /home/deckweiss/Work/spiketime-accountant
    /home/deckweiss/Uni/Aktuell/MCIM/Aufgaben/Lösungen/Klausurvorbereitung
    /home/deckweiss/Uni/Aktuell/MCIM/Aufgaben/Lösungen/SetupExample
    /home/deckweiss/Work/datevwebapp

========== Filter Jetbrains Apps ==========
```



I am not sure why it isn't working out of the box for me, but I am happy with the workaround. Thanks for your time and effort - I am happy that I can start my projects from krunner now :D 

If you need me to provide you any further info - or try something out, let me know

**Comment by alex1701c** [comment]
Sorry, for not catching up on this. I have read that it works for you and then it was out of my mind ;)

I will add some automated tests and then merge that into master. After that I will look into the autodetection.

**Comment by alex1701c** [comment]
The autodetection got completely rewritten. If there are any issues with the state of master, please open a new issues.
