### ISSUE TITLE
IDEA  2020.3 I won't support it

### ISSUE THREAD

**Issue by yinxiulong** [alex1701c/JetBrainsRunner#16]
IDEA  2020.3 I won't support it 
recentProjects.xml  This node is not in the file

```
    <option name="recentPaths">
      <list>
         ................................
     </list>
    </option>
````

**Comment by alex1701c** [comment]
Not sure what you mean, do you have parsing issues like in https://github.com/alex1701c/JetBrainsRunner/issues/14?

**Comment by yinxiulong** [comment]
Idea 2020.3 recentProjects.xml The file structure has changed. There is no < option name = "recentpaths" > node. You can try it with idea 2020.3

**Comment by yinxiulong** [comment]
The structure is like this


```
<application>
  <component name="RecentProjectsManager">
    <option name="additionalInfo">
      <map>
        <entry key="/run/media/yinxiulong/Data/nas/boot-mybatis-vue">
          <value>
            <RecentProjectMetaInfo frameTitle="boot-mybatis-vue – GenUtils.java" projectWorkspaceId="1lCOmyZlr5z67M4vzzEBYJY14Fs">
              <option name="binFolder" value="$APPLICATION_HOME_DIR$/bin" />
              <option name="build" value="IU-203.5981.155" />
              <option name="buildTimestamp" value="1606775712760" />
              <frame x="648" y="92" width="1272" height="696" />
              <option name="productionCode" value="IU" />
              <option name="projectOpenTimestamp" value="1607159800228" />
            </RecentProjectMetaInfo>
          </value>
        </entry>
      </map>
    </option>
    <option name="lastProjectLocation" value="/run/media/yinxiulong/Data/nas" />
  </component>
</application>
```

**Comment by alex1701c** [comment]
Okay thanks, I will look into adjusting the XML parser.

**Comment by alex1701c** [comment]
Hey, can you please checkout & pull the `rewrite_xml_parsing` branch of the src/jetbrains-api submodule?

That should fix the compatibility with the new versions.

**Comment by yinxiulong** [comment]
I didn't find the branch you were talking about    rewrite_xml_parsing branch of the src/jetbrains-api

**Comment by yinxiulong** [comment]
I just updated to version 1.6, but I still can't afford to use idea 2020.3

**Comment by alex1701c** [comment]
I have just merged that into master. If you pull the latest state you should have the fix.

**Comment by yinxiulong** [comment]
![image](https://user-images.githubusercontent.com/26619335/102900556-6afb1880-44a7-11eb-8ed1-41f8cd9daa76.png)
I pull the latest code, recompile and install, still can't

**Comment by alex1701c** [comment]
Do you also have the latest state of the submodule (src/jetbrains-api)? And would you be so nice and provide the config file, then I can try to reproduce the issue.

And did you make sure to restart KRunner after installing (should be done automatically when using the scripts)

**Comment by yinxiulong** [comment]
Manjaro src]$ ls
CMakeLists.txt  config  jetbrains-api  jetbrainsrunner.cpp  jetbrainsrunner.h  jetbrainsrunner.png  plasma-runner-jetbrainsrunner.desktop.in

There are JetBrains API modules

**Comment by alex1701c** [comment]
But that does not check if it is properly updated ;-)

Maybe deleting the folder and cloning the repo and reinstalling it would be the easiest way.

**Comment by ovv** [comment]
After updating the submodule it now works fine

`git submodule update --remote`

It's still complaining about an update being available. I believe it's because https://github.com/alex1701c/JetBrainsRunner/blob/master/CMakeLists.txt#L5 was not updated

**Comment by alex1701c** [comment]
Yeah, that is a detail I forgot ;)

I also uploaded the archives with the submodules to the latest release.
